#!/bin/bash

# Keyboard
if [ $TERM != "linux" ]
then
    { setxkbmap -option 'caps:ctrl_modifier';xcape -e 'Caps_Lock=Escape'; }
    { setxkbmap -layout us,ru && setxkbmap -option 'grp:switch,grp:win_space_toggle'; }
    { setxkbmap -option "compose:ralt"; }
fi

# colors
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# aliases
[[ -f ~/.aliases.sh ]] && source ~/.aliases.sh 

# bashenv
[[ -f ~/.bashenv ]] && source ~/.bashenv 

# micromamba

if type micromamba &> /dev/null
then
    eval "$(micromamba shell hook --shell zsh)"
fi
